config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clients

  root 'clients#index'

end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  has_one :accomodation_type
  belongs_to :client
end

app/models/accomodation_type.rb
class AccomodationType < ActiveRecord::Base
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :accomodation
  has_many :payment
end

app/models/client.rb
class Client < ActiveRecord::Base
    has_many :accomodation
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  has_one :plan
  has_one :payment_type
  belongs_to :ad
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.'}
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, html: { class: 'form' } do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Client', class:'btn btn-primary pull-right' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<% content_for :page_header do %>Editing Client<% end %>

<div class="col-lg-6">

    <%= render 'form' %>

    <%= link_to 'Show', @client, class:'btn btn-default' %> |
    <%= link_to 'Back', clients_path, class:'btn btn-info' %>


</div>

app/views/clients/index.html.erb
<% content_for :page_header do %>Listing Clients<% end %>
<!--
<ol class="breadcrumb">
    <li>
        <i class="fa fa-users"></i>&nbsp;&nbsp;<a href="/clients" class="btn-link">Clients</a>
    </li>
    <li class="active">
        <i class="fa fa-list"></i> List
    </li>
</ol>
-->
<% if !notice.nil? %>
    <div id="notice" class="alert"><%= notice %></div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client, class:'btn btn-sm btn-default'%></td>
        <td><%= link_to 'Edit', edit_client_path(client), class:'btn btn-sm btn-warning' %></td>
        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Client', new_client_path, class:'btn btn-primary'%>

app/views/clients/new.html.erb
<% content_for :page_header do %>New Client<% end %>

<%= render 'form' %>

<%= link_to 'Back', clients_path, class:'btn btn-info' %>

app/views/clients/show.html.erb
<% content_for :page_header do %>Showing Client<% end %>

<div class="row col-lg-6">
    <div class="well">
        <p id="notice"><%= notice %></p>

        <div class="form-group">
            <strong>First name:</strong>
            <%= @client.first_name %>
        </div>

        <div class="form-group">
            <strong>Last name:</strong>
            <%= @client.last_name %>
        </div>

        <div class="form-group">
            <strong>Email:</strong>
            <%= @client.email %>
        </div>

        <%= link_to 'Edit', edit_client_path(@client), class:'btn btn-warning' %>
        |
        <%= link_to 'Back', clients_path, class:'btn btn-info' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <head>
        <title>VickyOnRails</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>
        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">SB Admin</a>
                </div>

                <%= render 'shared/left_top_menu' %>

                <%= render "shared/menu"  %>

                <!-- /.navbar-collapse -->
            </nav>

            <div id="page-wrapper">

                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <h1 class="page-header">
                                        <%= yield :page_header %>
                                    </h1>
                                </div>
                            </div>
                            <%= yield %>
                        </div>
                    </div>
                    <!-- /.row -->

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->

    </body>

</html>

app/views/shared/_left_top_menu.erb
<!-- Top Menu Items -->
<ul class="nav navbar-right top-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu message-dropdown">
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Smith</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Smith</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Smith</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-footer">
                <a href="#">Read All New Messages</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu alert-dropdown">
            <li>
                <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
            </li>
            <li>
                <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">View All</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
            </li>
        </ul>
    </li>
</ul>

app/views/shared/_menu.erb
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li>
            <a href="/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
        </li>
        <li class="active">
            <a href="<%= clients_path %>"><i class="fa fa-fw fa-users"></i> Clients</a>
        </li>
        <!-- <li>
            <a href="charts.html"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
        </li>
        <li>
            <a href="tables.html"><i class="fa fa-fw fa-table"></i> Tables</a>
        </li>
        <li>
            <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
        </li>
        <li>
            <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
        </li>
        <li>
            <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
        </li>
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="demo" class="collapse">
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
                <li>
                    <a href="#">Dropdown Item</a>
                </li>
            </ul>
        </li> -->

        <!-- <li>
            <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
        </li> -->
    </ul>
</div>